/* Generated by tools/build.py. Scope-isolated cache; never intercept other projects. */
const VERSION='13f81c03f108';
const PREFIX='tabibi:'+new URL(self.registration.scope).pathname+':';
const CACHE=PREFIX+VERSION;
const FILES=["404.html", "about.html", "assets/fonts/OFL.txt", "assets/fonts/Tajawal-Bold.ttf", "assets/fonts/Tajawal-Regular.ttf", "assets/icons/apple-touch-icon.png", "assets/icons/icon-192.png", "assets/icons/icon-512.png", "assets/icons/icon.svg", "assets/icons/maskable-512.png", "assets/social-card.png", "assets/vendor/leaflet/LICENSE", "assets/vendor/leaflet/images/layers-2x.png", "assets/vendor/leaflet/images/layers.png", "assets/vendor/leaflet/images/marker-icon-2x.png", "assets/vendor/leaflet/images/marker-icon.png", "assets/vendor/leaflet/images/marker-shadow.png", "assets/vendor/leaflet/leaflet.css", "assets/vendor/leaflet/leaflet.js", "contact.html", "css/style.css", "data/communes.json", "data/doctors.json", "data/search-index.json", "data/specialties.json", "data/stats.json", "data/wilayas.json", "doctors.html", "favorites.html", "index.html", "install.html", "js/app.js", "js/core.js", "js/directory.js", "js/map.js", "js/pwa.js", "js/theme.js", "manifest.webmanifest", "map.html", "offline.html", "privacy.html", "specialties/cardiology.html", "specialties/dentistry.html", "specialties/dermatology.html", "specialties/endocrinology.html", "specialties/ent.html", "specialties/gastroenterology.html", "specialties/general.html", "specialties/gynecology.html", "specialties/index.html", "specialties/internal-medicine.html", "specialties/nephrology.html", "specialties/neurology.html", "specialties/oncology.html", "specialties/ophthalmology.html", "specialties/orthopedics.html", "specialties/pediatrics.html", "specialties/psychiatry.html", "specialties/pulmonology.html", "specialties/radiology.html", "specialties/rheumatology.html", "specialties/urology.html", "specialty.html", "stats.html", "terms.html"];
const absolute=path=>new URL(path,self.registration.scope).href;
const ALLOWED=new Set(FILES.map(absolute));
self.addEventListener('install',event=>event.waitUntil((async()=>{
  const cache=await caches.open(CACHE);
  try{await cache.addAll(FILES.map(path=>new Request(absolute(path),{cache:'reload'})));}
  catch(error){await caches.delete(CACHE);throw error;}
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
  const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith(PREFIX)&&n!==CACHE).map(n=>caches.delete(n)));await self.clients.claim();
})()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
  const request=event.request;const u=new URL(request.url);const scope=new URL(self.registration.scope);
  if(request.method!=='GET'||u.origin!==scope.origin||!u.pathname.startsWith(scope.pathname))return;
  const key=new URL(u);key.search='';key.hash='';if(key.pathname.endsWith('/'))key.pathname+='index.html';
  // Unknown resources are never replaced with HTML unless this is a navigation.
  if(request.mode!=='navigate'&&!ALLOWED.has(key.href))return;
  event.respondWith((async()=>{
    const cache=await caches.open(CACHE);
    // Versioned immutable app shell: the next worker installs an atomic new shell.
    if(request.mode!=='navigate'&&!u.pathname.includes('/data/')){
      const saved=await cache.match(key.href);if(saved)return saved;return fetch(request);
    }
    try{
      const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);
      let response;try{response=await fetch(request,{signal:controller.signal});}finally{clearTimeout(timer);}
      // Preserve actual HTTP errors (especially 404), never turn missing pages into 200.
      if(response.ok&&ALLOWED.has(key.href))await cache.put(key.href,response.clone()).catch(()=>{});
      return response;
    }catch{
      const saved=await cache.match(key.href);if(saved)return saved;
      if(request.mode==='navigate')return (await cache.match(absolute('offline.html'))) || new Response('Offline',{status:503});
      return new Response(JSON.stringify({error:'offline'}),{status:503,headers:{'Content-Type':'application/json'}});
    }
  })());
});
