import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,distance,openStatus,selectDoctors} from '../js/core.js';
test('Arabic diacritics, alif and French accents normalize',()=>{assert.equal(normalize('أَحْمَد'),normalize('احمد'));assert.equal(normalize('Pédiatrie'),normalize('pediatrie'));});
test('distance accepts zero and rejects missing coordinates',()=>{assert.equal(distance({lat:0,lng:0},{lat:0,lng:0}),0);assert.equal(distance(null,{lat:0,lng:0}),null);assert.ok(Math.abs(distance({lat:0,lng:0},{lat:0,lng:1})-111.195)<.01);});
test('hours use Algeria time and closing boundary, unknown/offline are not closed',()=>{const hours={mon:[['08:00','12:00'],['14:00','18:00']]};assert.match(openStatus(hours,new Date('2026-09-14T07:00:00Z')),/^مفتوح/);assert.match(openStatus(hours,new Date('2026-09-14T11:00:00Z')),/^مغلق/);assert.match(openStatus(hours,new Date('2026-09-14T13:00:00Z')),/^مفتوح/);assert.equal(openStatus(null),'المواعيد غير مؤكدة');assert.equal(openStatus(hours,new Date(),false),'المواعيد غير مؤكدة');});
const data={doctors:[{id:'a',name:'أحمد',specialtyIds:['cardio'],verifiedAt:'2026-09-16',practices:[{wilayaCode:'16',coordinates:{lat:0,lng:0}},{wilayaCode:'31',coordinates:{lat:1,lng:1}}]},{id:'b',name:'سارة',specialtyIds:['pediatrics'],verifiedAt:'2026-09-17',practices:[{wilayaCode:'31',coordinates:null}]}],index:[{id:'a',text:'أحمد cardiologie القلب'},{id:'b',text:'سارة pediatrie'}]};
test('filters choose matching practice and do not mutate source records',()=>{const original=JSON.stringify(data);const rows=selectDoctors(data,{wilaya:'31',spec:'cardio',sort:'distance'},{lat:0,lng:0});assert.equal(rows.length,1);assert.equal(rows[0].practice.wilayaCode,'31');assert.ok(rows[0].km>150);assert.equal(JSON.stringify(data),original);});
test('search AND tokens, favorites and missing coordinates',()=>{assert.equal(selectDoctors(data,{q:'احمد القلب'}).length,1);assert.equal(selectDoctors(data,{q:'احمد اسنان'}).length,0);assert.equal(selectDoctors(data,{},null,new Set(['b']))[0].doctor.id,'b');const rows=selectDoctors(data,{sort:'distance'},{lat:0,lng:0});assert.equal(rows[0].doctor.id,'a');assert.equal(rows[1].km,null);});
