import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {availability,summarize,scheduleText,selectDoctors} from '../js/core.js';
const read=name=>JSON.parse(fs.readFileSync(new URL('../data/'+name+'.json',import.meta.url),'utf8'));
const data={doctors:read('specialties').flatMap(s=>read('doctors/'+s.id)),specialties:read('specialties'),index:read('search-index')};
test('two initial records per specialty with no fabricated verification',()=>{assert.equal(data.doctors.length,40);for(const s of data.specialties)assert.equal(data.doctors.filter(d=>d.specialtyIds.includes(s.id)).length,2);for(const d of data.doctors){assert.equal(d.isPlaceholder,true);assert.equal(d.verificationStatus,'unverified');assert.equal(d.verifiedAt,undefined);assert.equal(d.sourceUrl,undefined);assert.match(d.practices[0].phones[0],/^\+213000000\d{3}$/);}});
test('Algeria Sunday opening, Thursday closing, and weekend boundaries',()=>{const hours=data.doctors[0].practices[0].openingHours;for(const [iso,expected] of [['2026-09-20T07:59:59Z','closed'],['2026-09-20T08:00:00Z','open'],['2026-09-17T13:59:59Z','open'],['2026-09-17T14:00:00Z','closed'],['2026-09-18T09:00:00Z','closed'],['2026-09-19T09:00:00Z','closed']])assert.equal(availability(hours,new Date(iso)).state,expected);assert.equal(availability(hours,new Date(),false).state,'unknown');assert.deepEqual(scheduleText(hours),{days:'الأحد – الخميس',hours:'09:00 – 15:00'});});
test('live stats count doctors once, separate initial and verified, reflect time/offline',()=>{const open=summarize(data,new Date('2026-09-20T09:00:00Z'));assert.equal(open.total,40);assert.equal(open.specialties,20);assert.equal(open.wilayas,4);assert.equal(open.open,40);assert.equal(open.initial,40);assert.equal(open.verified,0);assert.ok(Object.values(open.bySpecialty).every(n=>n===2));assert.equal(summarize(data,new Date('2026-09-18T09:00:00Z')).open,0);assert.equal(summarize(data,new Date(),false).open,'—');});
test('demo profiles have no Physician markup or sitemap entries; phone and route present',()=>{const sitemap=fs.readFileSync(new URL('../sitemap.xml',import.meta.url),'utf8');for(const d of data.doctors){const html=fs.readFileSync(new URL('../doctors/'+d.slug+'.html',import.meta.url),'utf8');assert.match(html,/noindex,follow/);assert.doesNotMatch(html,/"@type": "Physician"/);assert.ok(!sitemap.includes(d.slug));assert.match(html,/<bdi dir="ltr">\+213/);assert.match(html,/href="tel:/);assert.match(html,/maps\/dir\/\?api=1&amp;destination=/);assert.match(html,/data-hours=/);}});
test('sort recent works with unverified demo updatedAt, search remains scoped',()=>{assert.equal(selectDoctors(data,{sort:'recent'}).length,40);assert.equal(selectDoctors(data,{spec:'cardio'}).length,2);assert.equal(selectDoctors(data,{q:'Cardiologie'}).length,2);});
