import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
function runtime(scope='https://example.test/tabibi/'){
 const events={};const buckets=new Map();const deletions=[];let online=true;let status=200;let skipped=false;
 const caches={async open(name){if(!buckets.has(name))buckets.set(name,new Map());const map=buckets.get(name);return {async addAll(requests){for(const r of requests)map.set(r.url,new Response(r.url));},async match(url){return map.get(typeof url==='string'?url:url.url)?.clone();},async put(url,response){map.set(url,response);}};},async keys(){return [...buckets.keys()];},async delete(name){deletions.push(name);return buckets.delete(name);}};
 const self={registration:{scope},clients:{async claim(){}},skipWaiting(){skipped=true;},addEventListener(type,fn){events[type]=fn;}};
 vm.runInNewContext(source,{self,caches,URL,Request,Response,AbortController,setTimeout,clearTimeout,fetch:async req=>{if(!online)throw Error('Offline');return new Response('NETWORK '+(req.url||req),{status});}});
 async function trigger(type,props={}){let result;events[type]({...props,waitUntil:p=>{result=p;},respondWith:p=>{result=p;}});return await result;}
 return {trigger,buckets,deletions,setOnline:v=>{online=v;},setStatus:v=>{status=v;},get skipped(){return skipped;}};
}
const req=(path,mode='navigate',method='GET')=>({url:'https://example.test'+path,mode,method});
test('PWA install precaches shell, scoped pages, and required assets',async()=>{const r=runtime();await r.trigger('install');assert.equal(r.buckets.size,1);const files=[...r.buckets.values()][0];assert.ok(files.has('https://example.test/tabibi/index.html'));assert.ok(!files.has('https://example.test/tabibi/data/doctors/cardio.json'));assert.ok(!files.has('https://example.test/tabibi/doctors/demo-cardiology-1.html'));assert.ok(!files.has('https://example.test/tabibi/specialties/cardiology.html'));assert.ok(files.has('https://example.test/tabibi/assets/icons/icon-192.png'));assert.equal(r.skipped,false);});
test('offline root, query strings and specialty pages resolve cached documents',async()=>{const r=runtime();await r.trigger('install');await r.trigger('fetch',{request:req('/tabibi/specialties/cardiology.html')});r.setOnline(false);for(const path of ['/tabibi/','/tabibi/doctors.html?q=test','/tabibi/specialties/cardiology.html']){const response=await r.trigger('fetch',{request:req(path)});assert.equal(response.status,200);assert.ok(!(await response.text()).includes('offline.html'));}});
test('unknown offline navigation has fallback; unknown assets are untouched',async()=>{const r=runtime();await r.trigger('install');r.setOnline(false);assert.match(await (await r.trigger('fetch',{request:req('/tabibi/not-saved.html')})).text(),/offline.html/);assert.equal(await r.trigger('fetch',{request:req('/tabibi/missing.js','cors')}),undefined);});
test('real HTTP 404 is preserved and other sites/POST ignored',async()=>{const r=runtime();await r.trigger('install');r.setStatus(404);assert.equal((await r.trigger('fetch',{request:req('/tabibi/missing.html')})).status,404);assert.equal(await r.trigger('fetch',{request:req('/another-project/')}),undefined);assert.equal(await r.trigger('fetch',{request:req('/tabibi/','navigate','POST')}),undefined);});
test('activation removes only caches owned by this scope; update requires explicit message',async()=>{const r=runtime();r.buckets.set('tabibi:/tabibi/:old',new Map());r.buckets.set('tabibi:/other/:old',new Map());r.buckets.set('unrelated',new Map());await r.trigger('install');await r.trigger('activate');assert.deepEqual(r.deletions,['tabibi:/tabibi/:old']);await r.trigger('message',{data:{type:'SKIP_WAITING'}});assert.equal(r.skipped,true);});
test('works at origin root without a hard-coded project path',async()=>{const r=runtime('https://example.test/');await r.trigger('install');r.setOnline(false);assert.match(await (await r.trigger('fetch',{request:req('/')})).text(),/example.test\/index.html/);});

test('specialty data is fetched only when visited, then works offline',async()=>{const r=runtime();await r.trigger('install');const cache=[...r.buckets.values()][0];assert.ok(!cache.has('https://example.test/tabibi/data/doctors/cardio.json'));await r.trigger('fetch',{request:req('/tabibi/data/doctors/cardio.json','cors')});assert.ok(cache.has('https://example.test/tabibi/data/doctors/cardio.json'));assert.ok(!cache.has('https://example.test/tabibi/data/doctors/dental.json'));r.setOnline(false);assert.equal((await r.trigger('fetch',{request:req('/tabibi/data/doctors/cardio.json','cors')})).status,200);assert.equal((await r.trigger('fetch',{request:req('/tabibi/data/doctors/dental.json','cors')})).status,503);});
